services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gravai-app
    ports:
      - "8000:8000"
    volumes:
      - .env:/app/.env
    restart: unless-stopped
    entrypoint: ["uv", "run", "fastapi", "run", "api/app.py", "--host", "0.0.0.0", "--port", "8000"]

  whisper:
    build:
      context: .
      dockerfile: Dockerfile.whisper
    container_name: whisper
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    entrypoint: ["./build/bin/whisper-server", "-m", "models/ggml-large-v3.bin", "--host", "0.0.0.0", "--language", $WHISPER_LANGUAGE, "--port", "8080"]
    